// Datos de ejemplo para RealCars Company - Automotora Premium
import type { Auto } from './types'

export const autos: Auto[] = [
  {
    id: '1',
    marca: 'Mercedes-Benz',
    modelo: 'C63 AMG',
    año: 2022,
    precio: 38000000,
    kilometraje: 75000,
    transmision: 'Automática',
    combustible: 'Gasolina',
    color: 'Negro',
    imagen: '/images/autos/mercedesC63AMG.jpeg',
    descripcion: 'Mercedes-Benz C63 AMG 2022, seminuevo con 75.000km, deportivo de lujo con motor V8 biturbo. Potencia y elegancia en cada detalle.',
    caracteristicas: [
      'Motor V8 Biturbo 4.0L',
      '510 HP de potencia',
      'Transmisión AMG SPEEDSHIFT MCT',
      'Suspensión AMG RIDE CONTROL',
      'Frenos AMG de alto rendimiento',
      'Interior cuero Nappa AMG',
      'Sistema audio Burmester',
      'Asientos deportivos AMG',
    ],
    estado: 'disponible',
    destacado: true,
  },
  {
    id: '2',
    marca: 'Mercedes-Benz',
    modelo: 'GLE 350',
    año: 2024,
    precio: 38000000,
    kilometraje: 0,
    transmision: 'Automática',
    combustible: 'Gasolina',
    color: 'Blanco',
    imagen: '/images/autos/mercedesgle350.jpeg',
    descripcion: 'Mercedes-Benz GLE 350 2024, 0km, SUV de lujo con tecnología avanzada y confort premium.',
    caracteristicas: [
      'Motor V6 3.0L biturbo',
      '296 HP de potencia',
      'Tracción integral 4MATIC',
      'Suspensión neumática Airmatic',
      'MBUX multimedia system',
      'Asientos eléctricos con memoria',
      'Cristales tintados',
      'Sistema de navegación GPS',
    ],
    estado: 'disponible',
    destacado: true,
  },
  {
    id: '3',
    marca: 'Mercedes-Benz',
    modelo: 'A45 S AMG',
    año: 2023,
    precio: 28000000,
    kilometraje: 25000,
    transmision: 'Automática',
    combustible: 'Gasolina',
    color: 'Gris',
    imagen: '/images/autos/mercedes a45s amg.jpeg',
    descripcion: 'Mercedes-Benz A45 S AMG 2023, seminuevo con 25.000km, hatchback deportivo de alto rendimiento con tecnología AMG.',
    caracteristicas: [
      'Motor 4 cilindros 2.0L AMG',
      '421 HP de potencia',
      'Transmisión AMG SPEEDSHIFT DCT',
      'Tracción integral AMG Performance 4MATIC+',
      'Suspensión AMG RIDE CONTROL',
      'Frenos AMG de cerámica',
      'Interior deportivo AMG',
      'Sistema de escape AMG Performance',
    ],
    estado: 'disponible',
    destacado: false,
  },
  {
    id: '4',
    marca: 'Land Rover',
    modelo: 'Defender',
    año: 2023,
    precio: 35000000,
    kilometraje: 18000,
    transmision: 'Automática',
    combustible: 'Diesel',
    color: 'Blanco',
    imagen: '/images/autos/landroverdefender.jpeg',
    descripcion: 'Land Rover Defender 2023, seminuevo con 18.000km, SUV todoterreno de leyenda con lujo moderno y capacidad off-road excepcional.',
    caracteristicas: [
      'Motor Diesel 3.0L 6 cilindros',
      '300 HP de potencia',
      'Tracción integral permanente',
      'Suspensión neumática adaptativa',
      'Sistema Terrain Response 2',
      'Interior cuero premium',
      'Sistema de navegación Pivi Pro',
      'Cámara 360° y sensores',
    ],
    estado: 'disponible',
    destacado: true,
  },
  {
    id: '5',
    marca: 'BMW',
    modelo: 'X6 M Competition',
    año: 2024,
    precio: 48000000,
    kilometraje: 0,
    transmision: 'Automática',
    combustible: 'Gasolina',
    color: 'Negro',
    imagen: '/images/autos/bmx6mcompetition.jpeg',
    descripcion: 'BMW X6 M Competition 2024, 0km, SUV coupé deportivo de alto rendimiento con tecnología M de BMW.',
    caracteristicas: [
      'Motor V8 4.4L TwinPower Turbo',
      '625 HP de potencia',
      'Transmisión M Steptronic 8 velocidades',
      'Tracción integral xDrive',
      'Suspensión M adaptativa',
      'Frenos M de cerámica opcionales',
      'Interior cuero Merino',
      'Sistema iDrive 8.0',
    ],
    estado: 'disponible',
    destacado: true,
  },
]